### ISSUE TITLE
Time Picker Issue

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#18]
**Describe the bug**
For **All** Time Pickers:
For example: 
for ‘what time did you go to bed?’ and you click on numbers, you can’t type them in – have to go to ‘pick time’ instead , and then it doesn’t fill the field

**To Reproduce**
1. Go to Question 4 of 14/ 6 of 13/  7 of 13 on sleep Diary 
2. Click on 'Pick Time'
3. Scroll down to 'works'
4. See error: Doesn't display time in Time window next to button "Pick Time" ---> still shows 00:00

**Expected behavior**
To show time that I have chosen. 

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: 11.4.1

**Additional context**
Time Picker is cool ;) 
Note: e.g., for Qs it shows 4 of 14 BUT for Qs it shows 6 of 13

**Comment by alexlaurence** [comment]
Hi Melanie, this issue should be fixed. Are you using the latest build? I just uploaded it an hour ago.

Also patients shouldn't be typing in their responses for time in order for everyone to use a standard format (24 HR, HH:MM). They must click on the pick time button.

**Comment by MK3112** [comment]
Hi Ash, no Jamie was using the last one and not the new one.

I will downlaod it in a bit. Just, making the other notes ☺
If I don’t have the same issue I will just delete the comment is that ok?

And she didn’t want to type, but when she used the time pickers she was able to pick the time but it still showed as 00:00 in the display instead of 05:00
